name: Valist Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm --prefix client ci
      - name: build
        run: npm run --prefix client build
      - uses: valist-io/valist-github-action@v2.1.0
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: javyer
          project: yieldshare
          release: 0.0.2
          files: 'client/build/**'